name: KitPvP
author: TheFl4me
version: 8.0.2
main: com.minecraft.plugin.elite.kitpvp.KitPvP
depend: [General, WorldEdit, WorldGuard]
softdepend: [General, Punish, NoHax, WorldEdit, WorldGuard]
commands:
    freekits:
    kit:
    kitinfo:
      aliases: [checkkit]