name: KitPvP
author: TheFl4me
version: 8.7.11
main: com.minecraft.plugin.elite.kitpvp.KitPvP
depend: [General, WorldEdit, WorldGuard]
commands:
    setduelspawn:
    setduellocation:
      aliases: [setduelloc]
    sethologram:
      aliases: [setholo]