package com.minecraft.plugin.elite.kitpvp;

import com.minecraft.plugin.elite.general.api.interfaces.LanguageNode;

public enum KitPvPLanguage implements LanguageNode {

    SCOREBOARD_TITLE,
    SCOREBOARD_KIT,
    SCOREBOARD_KILLS,
    SCOREBOARD_DEATHS,
    SCOREBOARD_ELO,

    REGION_SPAWN_LEAVE,

    SPAWN_TOOL,

    HOLOGRAM_USAGE,
    HOLOGRAM_SET,
    HOLOGRAM_FEAST,
    HOLOGRAM_EHG,

    DUEL_SET_SPAWN,
    DUEL_SET_LOCATION_SET,
    DUEL_SET_LOCATION_USAGE,

    DUEL_REQUEST_RECEIVED,
    DUEL_REQUEST_SENT,
    DUEL_REQUEST_ACCEPTED,
    DUEL_REQUEST_COOLDOWN,
    DUEL_ALREADY,
    DUEL_WIN,
    DUEL_LOSE,

    DUEL_GUI_TITLE,
    DUEL_GUI_WAIT,
    DUEL_GUI_EDIT,
    DUEL_GUI_ACCEPT,
    DUEL_GUI_DONE,
    DUEL_GUI_CANCEL,
    DUEL_GUI_EDITOR,
    DUEL_GUI_STANDBY,
    DUEL_GUI_RE_CRAFT,

    DUEL_TOOL,
    DUEL_TOOL_CUSTOM,
    DUEL_TOOL_DEFAULT,
    DUEL_TOOL_QUEUE,
    DUEL_TOOL_QUEUE_CANCEL,

    DEATH,
    KILL_STREAK,
}
