package com.minecraft.plugin.elite.general;

import com.minecraft.plugin.elite.general.api.interfaces.LanguageNode;

public enum GeneralLanguage implements LanguageNode {

    RELOAD,
    NOPERM,
    ONLY_PLAYER,
    NO_TARGET,
    NEVER_JOINED,
    LEFT,
    JOINED,
    ARG_INVALID,
    SYNTAX,

    UNIT_YEAR,
    UNIT_YEAR_PLURAL,
    UNIT_MONTH,
    UNIT_MONTH_PLURAL,
    UNIT_WEEK,
    UNIT_WEEK_PLURAL,
    UNIT_DAY,
    UNIT_DAY_PLURAL,
    UNIT_HOUR,
    UNIT_HOUR_PLURAL,
    UNIT_MINUTE,
    UNIT_MINUTE_PLURAL,
    UNIT_SECOND,
    UNIT_SECOND_PLURAL,

    HELP,

    HEADER,
    FOOTER,

    LANGUAGE,
    LANGUAGE_NULL,
    LANGUAGE_USAGE,

    LEVEL_UP,

    DAMAGE_PERCENT,

    STAFF_UPDATED,
    STAFF_NULL,
    STAFF_USAGE,
    STAFF_CLEAR_USAGE,

    GUI_BACK,

    DB_CHECK,
    DB_CHECK_FAIL,

    RANK_SET,
    RANK_SET_YOU,
    RANK_INVALID,
    RANK_USAGE,

    WELCOME,
    NOT_ADMIN_MODE,

    CLEAR,
    CLEAR_NOPERM,

    SPAWN_SET,

    INVIS_USAGE,
    INVIS_NOPERM,
    INVIS_INVIS,
    INVIS_VIS,
    INVIS_VIS_ALREADY,

    WATCH_WATCHING,

    MODE_STILL_ADMIN,
    MODE_STILL_WATCH,

    INVSEE_USAGE,

    SPEED_USAGE,
    SPEED_FLY,
    SPEED_WALK,

    HEAD_USAGE,

    PVP_ENABLED,
    PVP_DISABLED,
    PVP_DISABLED_ON_HIT,

    GAMEMODE_SET_OTHER,
    GAMEMODE_SET_YOU,
    GAMEMODE_USAGE,

    BUILD_ENABLED,
    BUILD_DISABLED,

    PING,

    CLEAR_LAG,

    KILL_ALL,

    STATS,

    JOIN_FULL,
    JOIN_WHITELIST,

    PUNISH_USAGE,
    PUNISH_NOPERM,

    PUNISH_BAN_NOPERM,

    BAN_WARNING,
    BAN_BANNED,
    BAN_SCREEN,
    BAN_INFO,
    BAN_INFO_PAST,

    UNBAN_UNBANNED,
    UNBAN_NOT_BANNED,
    UNBAN_USAGE,

    IP_USAGE,

    KICK_USAGE,
    KICK_KICKED,
    KICK_SCREEN,
    KICK_NOPERM,

    MUTE_MUTED,
    MUTE_MUTED_ON_TALK,
    MUTE_DISPLAY,
    MUTE_INFO,
    MUTE_INFO_PAST,

    UNMUTE_UNMUTED,
    UNMUTE_UNMUTED_YOU,
    UNMUTE_NOT_MUTED,
    UNMUTE_USAGE,

    REPORT_STAFF,
    REPORT_CONFIRMED,
    REPORT_NOT_ONLINE,
    REPORT_USAGE,
    REPORT_COOLDOWN,
    REPORT_ERROR_SELF,
    REPORT_ERROR_STAFF,
    REPORT_ERROR_NONE,

    REPORT_LIST,

    REPORT_CLEAR,
    REPORT_CLEAR_EMPTY,
    REPORT_CLEAR_USAGE,

    REPORT_GUI_TITLE,
    REPORT_GUI_HACKING,
    REPORT_GUI_BUG,
    REPORT_GUI_TEAM,
    REPORT_GUI_STATS,

    INFO_USAGE,
    INFO_GUI_ERROR,
    INFO_GUI_ADMIN,
    INFO_GUI_TIME,
    INFO_GUI_STATS,
    INFO_GUI_MUTES,
    INFO_GUI_BANS,
    INFO_GUI_REPORTS,
    INFO_GUI_ALTS,
    INFO_GUI_REPORTS_REPORT,

    CLAN_CREATED,
    CLAN_EXIST,
    CLAN_EXIST_NOT,
    CLAN_NAME_MAX_SIZE,
    CLAN_HAS_CLAN,
    CLAN_DELETED,
    CLAN_RANK_ERROR,
    CLAN_INVITE_SENT,
    CLAN_INVITE_RECEIVED,
    CLAN_INVITE_RECEIVED_CLICK_DENY,
    CLAN_INVITE_RECEIVED_CLICK_ACCEPT,
    CLAN_INVITE_ALREADY,
    CLAN_INVITE_NOT_OTHER,
    CLAN_INVITE_NOT_YOU,
    CLAN_INVITE_REVOKED,
    CLAN_INVITE_ACCEPT,
    CLAN_INVITE_DENY,
    CLAN_PROMOTED,
    CLAN_PROMOTED_ALREADY,
    CLAN_DEMOTED,
    CLAN_DEMOTED_ALREADY,
    CLAN_NOT_SAME,
    CLAN_HIGHER_RANK,
    CLAN_KICKED,
    CLAN_LEAVE,
    CLAN_USAGE,
    CLAN_CHAT_USAGE,
    CLAN_NONE,
    CLAN_HELP,

    SKIT_USAGE,
    SKIT_APPLY,
    SKIT_CREATE,
    SKIT_DELETE,
    SKIT_NULL,
    SKIT_EXISTS,

    AFK_TRUE,
    AFK_FALSE,

    RULES_AGREED_NOT,
    RULES_TITLE,
    RULES_AGREED,
    RULES_AGREED_ALREADY,

    MSG_USAGE_TELL,
    MSG_USAGE_REPLY,
    MSG_AFK,
    MSG_PARTNER_LEFT,
    MSG_REPLY_NULL,

    SAY_USAGE,

    CHAT_LINKS,
    CHAT_SWEAR,
    CHAT_CLEAR,
    CHAT_ENABLED,
    CHAT_DISABLED,
    CHAT_DISABLED_ON_TALK,
    CHAT_LOG_USAGE,

    PARTY_CREATED,
    PARTY_ALREADY,
    PARTY_DELETED,
    PARTY_NOT_CREATOR,
    PARTY_INVITE,
    PARTY_INVITE_RECEIVED,
    PARTY_INVITE_RECEIVED_CLICK_ACCEPT,
    PARTY_INVITE_RECEIVED_CLICK_DENY,
    PARTY_INVITE_ALREADY,
    PARTY_INVITE_NULL,
    PARTY_INVITE_NOT_YOU,
    PARTY_INVITE_REVOKED,
    PARTY_INVITE_ACCEPT,
    PARTY_INVITE_DENY,
    PARTY_NOT_SAME,
    PARTY_KICKED,
    PARTY_LEAVE,
    PARTY_ALREADY_OTHER,
    PARTY_USAGE,
    PARTY_NONE_YOU,
    PARTY_CHAT_USAGE,
    PARTY_HELP,

    ACHIEVEMENT_UNLOCKED,
    ACHIEVEMENT_FIRST_MSG,
    ACHIEVEMENT_KILLER,
    ACHIEVEMENT_PRESTIGE,
    ACHIEVEMENT_MAX_PRESTIGE,
    ACHIEVEMENT_STAFF_KILL,
    ACHIEVEMENT_ADMIN_KIll,
    ACHIEVEMENT_MEDIA_KILL,
    ACHIEVEMENT_MAX_PRESTIGE_KILL,
    ACHIEVEMENT_BLOODTHIRSTY,
    ACHIEVEMENT_INVINCIBLE,
    ACHIEVEMENT_NUCLEAR,
    ACHIEVEMENT_GOD,
    ACHIEVEMENT_LAST_RESORT,
    ACHIEVEMENT_LONG_SHOT,
    ACHIEVEMENT_BACKSTAB,

    SPY_ENABLED,
    SPY_DISABLED,

    APPLICATION_LINK,

    SUPPORT_REQUEST_STAFF,
    SUPPORT_REQUEST_SENT,
    SUPPORT_CONFIRMED_YOU,
    SUPPORT_CONFIRMED_STAFF,
    SUPPORT_END,
    SUPPORT_SELF,
    SUPPORT_ALREADY,
    SUPPORT_USAGE,
    SUPPORT_NO_REQUEST,
    SUPPORT_COOLDOWN,
    SUPPORT_CHAT_NULL,

    MENU_GUI_STAFF,
    MENU_GUI_ACHIEVEMENTS,
    MENU_GUI_FAQ,
    MENU_GUI_APPLICATION,
    MENU_GUI_STATS,
    MENU_GUI_UPDATE,

    MENU_GUI_BACK,
    MENU_GUI_TITLE,

    MENU_GUI_APPLICATION_APPLY,
    MENU_GUI_APPLICATION_MOD,
    MENU_GUI_APPLICATION_SUPPORTER,
    MENU_GUI_APPLICATION_BUILDER,

    MENU_GUI_STATS_GENERAL,
    MENU_GUI_STATS_ACTIVITY,
    MENU_GUI_STATS_TIME,
    MENU_GUI_STATS_PRESTIGE_SET,
    MENU_GUI_STATS_PRESTIGE_LOCKED,

    MENU_GUI_UPDATE_1,
    MENU_GUI_UPDATE_2,
    MENU_GUI_UPDATE_3,
    MENU_GUI_UPDATE_4,
    MENU_GUI_UPDATE_5,
    MENU_GUI_UPDATE_6,
    MENU_GUI_UPDATE_7,

    MENU_GUI_FAQ_RULES,
    MENU_GUI_FAQ_LEVELS,
    MENU_GUI_FAQ_STORE,
    MENU_GUI_FAQ_TEAMSPEAK,
    MENU_GUI_FAQ_UNBAN,
    MENU_GUI_FAQ_SUPPORT,

    MENU_GUI_FAQ_RULES_MODS,
    MENU_GUI_FAQ_RULES_CHAT,
    MENU_GUI_FAQ_RULES_TEAMS,
    MENU_GUI_FAQ_RULES_TERMS,

    MENU_GUI_FAQ_LEVELS_LEVELS,
    MENU_GUI_FAQ_LEVELS_PRESTIGE,
    MENU_GUI_FAQ_LEVELS_TOKENS,
    MENU_GUI_FAQ_LEVELS_PRESTIGE_CHANGE,
    MENU_GUI_FAQ_LEVELS_LEVEL_MAX,
    MENU_GUI_FAQ_LEVELS_PRESTIGE_MAX,
    MENU_GUI_FAQ_LEVELS_COLORS,

    MENU_GUI_FAQ_STORE_KITS,

    MENU_GUI_FAQ_TEAMSPEAK_WHAT,
    MENU_GUI_FAQ_TEAMSPEAK_WHERE,
    MENU_GUI_FAQ_TEAMSPEAK_IP,

    MENU_GUI_FAQ_UNBAN_UNBAN,
    MENU_GUI_FAQ_UNBAN_UNMUTE,
    MENU_GUI_FAQ_UNBAN_WHERE,

    MENU_GUI_STAFF_PREFIX,
    MENU_GUI_STAFF_ADMINS,
    MENU_GUI_STAFF_MODS,
    MENU_GUI_STAFF_SUPPORTERS,
    MENU_GUI_STAFF_BUILDERS,
    MENU_GUI_STAFF_YOU,
}
